### ISSUE TITLE
应当同时加一列提供当前的默认值。并且选择合适的默认值，达到适应大部分简单使用的目的。

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#118]
### 所属页面地址

https://docs.ark.online/GameplayObjects/AdvancedVehicle.html#%E4%BB%80%E4%B9%88%E6%98%AF%E9%AB%98%E7%BA%A7%E8%BD%AE%E5%BC%8F%E8%BD%BD%E5%85%B7

### 选中内容

取值范围

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

应当同时加一列提供当前的默认值。并且选择合适的默认值，达到适应大部分简单使用的目的。

**Comment by zuopengyou** [comment]
补充默认值信息以及单位说明
