### ISSUE TITLE
这类解释参数的地方，除了含义和范围，产品手册和API文档，都需要写明默认值以及【单位】。并选择适当的默认值，使得大部分简单应用的效果能对。

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#119]
### 所属页面地址

https://docs.ark.online/GameplayObjects/SwimmingArea.html

### 选中内容

游泳区域属性：

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

这类解释参数的地方，除了含义和范围，产品手册和API文档，都需要写明默认值以及【单位】。并选择适当的默认值，使得大部分简单应用的效果能对。

**Comment by liaoyuewu** [comment]
好的好的，这块会补上默认值以及对应单位
