### ISSUE TITLE
跟随的NPC不会跳下去

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#121]
### 所属页面地址

https://docs.ark.online/GameplayObjects/NavigationArea.html#%E5%A6%82%E4%BD%95%E8%AE%A9%E4%BA%BA%E5%BD%A2%E5%AF%B9%E8%B1%A1-npc-%E4%BD%BF%E7%94%A8%E5%AF%BB%E8%B7%AF%E6%8C%81%E7%BB%AD%E8%B7%9F%E9%9A%8F%E7%9B%AE%E6%A0%87%E7%A7%BB%E5%8A%A8

### 选中内容

创建一个脚本，使用follow()方法控制NPC跟随主角进行自动寻路

### 请选择反馈的问题类型

其他

### 补充说明

看下面的视频，NPC跟随主角，主角跳下去之后，NPC不会跟着跳下去。寻路能支持跳跃过障碍之类的吗？

**Comment by zuopengyou** [comment]
NPC是否执行跳跃需要在项目中自行编写脚本来实现，根据不同环境来制定AI策略，寻路功能无法自动执行这部分逻辑。
