### ISSUE TITLE
病句不通顺

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#123]
### 所属页面地址

https://docs.ark.online/GameplayObjects/Anchor.html

### 选中内容

【空锚点】提供用户去自定义对象锚点位置的功能，利用【空锚点】对象本身作为对象的锚点来使用。而且通过自动居中，顶点吸附和手动偏移3种偏移方式，提升【空锚点】作为父对象时在编辑状态下的操作便捷性。

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

“利用” 的主语是啥？
“而且”之后也没有主语。读起来太怪了。

**Comment by liaoyuewu** [comment]
哎呀这块应该是当时打字的问题，我记录这个问题，后续修改一下。
