### ISSUE TITLE
会有什么问题？如果不能动态生成为什么又有对应教学？

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#126]
### 所属页面地址

https://docs.ark.online/GameplayObjects/BlockingArea.html#%E5%AF%B9%E6%95%B4%E4%B8%AA%E7%A6%81%E8%A1%8C%E5%8C%BA%E8%AE%BE%E7%BD%AE%E9%80%9A%E8%A1%8C%E6%9D%83%E9%99%90

### 选中内容

不推荐动态生成

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

会有什么问题？如果不能动态生成为什么又有对应教学？

**Comment by liaoyuewu** [comment]
这个是我没描述清楚，禁行区动态生成如果边缘有角色的话会卡住，导致角色无法移动，这块我细化一下描述。
