### ISSUE TITLE
这个手册内容选择有问题，除了音效控制外，最应该加上的是怎么自己在网上检索合适的音效并且怎么上传到编辑器。

### ISSUE THREAD

**Issue by honsrx** [prodigytech-doc/product-docs#127]
### 所属页面地址

https://docs.ark.online/GameplayObjects/SoundEffect.html

### 选中内容

音效

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

这个手册内容选择有问题，除了音效控制外，最应该加上的是怎么自己在网上检索合适的音效并且怎么上传到编辑器。

**Comment by liaoyuewu** [comment]
好的，我下一版更新重新调整一下内容的选择和写作的偏向。
