### ISSUE TITLE
UICallOnly的资料极少，请补充说明

### ISSUE THREAD

**Issue by zaixia** [prodigytech-doc/product-docs#254]
### 所属页面地址

https://docs.ark.online/UI/UIWidget-BaseProperties.html#ts%E8%84%9A%E6%9C%AC

### 选中内容

UICallOnly装饰器

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

### 补充说明

教程、产品手册、文档、论坛中关于此装饰器的使用说明很少，麻烦补充一下。

**Comment by 756904658** [comment]
已更新到最新版本，辛苦再看下~
