### ISSUE TITLE
为啥这里的视频不是口袋方舟的演示

### ISSUE THREAD

**Issue by onionkingdom** [prodigytech-doc/product-docs#282]
### 所属页面地址

https://docs.ark.online/WorldObjects/Fog.html#%E7%8E%AF%E5%A2%83%E9%9B%BE%E9%A2%84%E8%AE%BE

### 选中内容

效果图：

### 请选择反馈的问题类型

缺少信息 - 我想了解更多信息

**Comment by Aries-MetaApp** [comment]
The document has been repaired, thank you for your proposal.
