### ISSUE TITLE
表格的md格式没搞对

### ISSUE THREAD

**Issue by ShallowAlley** [prodigytech-doc/product-docs#283]
### 所属页面地址

https://docs.ark.online/WorldObjects/Fog.html#%E6%98%AF%E5%90%A6%E5%90%AF%E7%94%A8

### 选中内容

| 枚举名称 | 英文名称 | 枚举值 | 说明 | | 默认 | Default | 0 | 默认效果，距离和浓度适中 | | 近景雾 | NearFog | 1 | 近处的环境雾，距离较短 | | 远景雾 | FarFog | 2 | 远处的环境雾，距离较远 | | 地下雾 | UndergroundFog | 3 | 黑暗的地下洞穴的环境效果 | | 默沙漠雾 | DesertFog | 4 | 沙漠地带的环境效果 |

### 请选择反馈的问题类型

小错误 - 有错别字/语句不通/链接打不开

**Comment by Aries-MetaApp** [comment]
The document has been repaired, thank you for your proposal.
